'use client'
/**
 * UNDERSTAND — "why this ad works," fetched from /api/ad-insight (generated by
 * Mello on first visit, cached forever). Shows a soft skeleton while thinking so
 * the visitor SEES the analysis being done for them — then the bullets land.
 */
import { useEffect, useState } from 'react'

const MUTED = '#68756b', LINE = '#e7ece7'

export default function Understand({ adId }: { adId: string }) {
  const [data, setData] = useState<{ headline: string; bullets: string[] } | null>(null)
  const [failed, setFailed] = useState(false)
  useEffect(() => {
    let alive = true
    fetch(`/api/ad-insight?adId=${encodeURIComponent(adId)}`)
      .then((r) => (r.ok ? r.json() : null))
      .then((d) => { if (!alive) return; if (d?.bullets?.length) setData(d); else setFailed(true) })
      .catch(() => { if (alive) setFailed(true) })
    return () => { alive = false }
  }, [adId])

  if (failed) return null
  return (
    <div style={{ margin: '18px 0', background: '#fff', border: `1px solid ${LINE}`, borderRadius: 14, padding: '16px 18px' }}>
      <div style={{ fontSize: 11, fontWeight: 800, letterSpacing: '.14em', color: MUTED, textTransform: 'uppercase', marginBottom: 8 }}>
        Understand · {data ? (data.headline || 'Why this ad works') : 'Mello is reading this ad…'}
      </div>
      {!data && (
        <div>
          {[86, 68, 78].map((w, i) => (
            <div key={i} style={{ height: 11, width: `${w}%`, background: '#eef2ec', borderRadius: 6, margin: '9px 0', animation: 'undpulse 1.2s ease-in-out infinite' }} />
          ))}
          <style>{`@keyframes undpulse{0%,100%{opacity:.5}50%{opacity:1}}`}</style>
        </div>
      )}
      {data && (
        <ul style={{ margin: 0, padding: 0, listStyle: 'none' }}>
          {data.bullets.map((b, i) => (
            <li key={i} style={{ display: 'flex', gap: 9, alignItems: 'baseline', padding: '5px 0', fontSize: 13.5, lineHeight: 1.55, color: '#2c342d', fontWeight: 550 }}>
              <span style={{ color: '#2f7a3f', fontWeight: 900, flexShrink: 0 }}>•</span>{b}
            </li>
          ))}
        </ul>
      )}
    </div>
  )
}
