-- 130 — Discovery "Newest" sort + "last N days" filter: composite partial index.
--
-- The Discovery feed reads discovery_ads_index WHERE has_creative = true (the drained ads that have
-- a creative to show). Sorting or filtering that set by RECENCY had NO supporting index:
--
--   • sort=newest  (ORDER BY days_running ASC)         → full sort of the whole has-creative set, OR
--     a wade down the (days_running) index skipping has_creative=false rows (the freshest ads are the
--     ~815K un-drained ones with no creative yet). Either way: 20-60s → the grid sat on skeletons and
--     the API 504'd. This is the "Newest shows oldest / index was busy" bug.
--   • days=7 / days=30  (WHERE days_running <= N)       → same wade: the planner walked whatever sort
--     index it had, filtering days_running<=N + has_creative row-by-row → 21s+ (only ~3 ads surfaced
--     before the client gave up).
--
-- Only perf_score-ordered queries were fast, because discovery_ads_perf_score_idx (mig 038) is hot AND
-- high-perf ads are older/established → already drained → have creatives (no wade).
--
-- The fix is a LEADING-EQUALITY composite (has_creative, days_running, ad_id). With WHERE
-- has_creative = true the planner does an Index Only Scan on the has_creative=true portion, already
-- ordered by days_running ASC, ad_id ASC — no Filter, no Sort:
--   WHERE has_creative ORDER BY days_running ASC, ad_id ASC LIMIT 60        (Newest)
--   WHERE has_creative AND days_running <= N ORDER BY days_running, ad_id   (last N days)
-- Proven live: LIMIT-60 plan cost dropped 9,676 → 2.03; the feed went from timeout → ~2s, 119 real
-- ads with days_running=0 (launched today) at the top.
--
-- NB: a PARTIAL index `(days_running, ad_id) WHERE has_creative` was tried first and the planner
-- REFUSED it — it kept backward-scanning the plain (days_running DESC) index with `Filter:
-- has_creative`, mis-costing the wade because it assumes has_creative is evenly spread across
-- days_running (it isn't — the freshest ads are the un-drained has_creative=false ones). A partial
-- index for an ORDER BY is fragile that way; the leading-equality composite is chosen reliably.
--
-- CONCURRENTLY = no table lock (safe on the live serving table); must be the ONLY statement in its
-- run (can't be in a transaction block). It builds in a few minutes under write load — the Supabase
-- SQL editor may show "Failed to fetch" (its HTTP request gives up) while the build finishes
-- server-side; verify with `select indisvalid from pg_index where indexrelid =
-- 'dai_hascre_days_asc'::regclass`. Run `analyze discovery_ads_index;` after so the planner picks it
-- up. Ideally pause crawl/drain first (pause-before-DDL) but CONCURRENTLY served fine live without it.
-- The route degrades Newest/date filters to a fast graceful "try again" until this lands.
create index concurrently if not exists dai_hascre_days_asc
  on discovery_ads_index (has_creative, days_running, ad_id);
